include $(BASEDIR)/Rules.mk

obj-$(CONFIG_VMM_SECURITY) += acm_hooks.o
obj-$(CONFIG_VMM_SECURITY) += aci_generator.o
obj-$(CONFIG_VMM_SECURITY) += acm_integrator.o
obj-$(CONFIG_VMM_SECURITY) += decision_cache.o
obj-$(CONFIG_VMM_SECURITY) += policy_conductor.o
obj-$(CONFIG_VMM_SECURITY) += te_extra.o
obj-$(CONFIG_VMM_SECURITY) += te.o
obj-$(CONFIG_VMM_SECURITY) += proprietary.o
obj-$(CONFIG_VMM_SECURITY) += blp.o

#obj-$(crash_debug) += gdbstub.o

include $(BASEDIR)/Post.mk
