/*
 * include/asm-arm/arch-imx/entry-macro.S
 *
 * Low-level IRQ helper macros for iMX-based platforms
 *
 * This file is licensed under  the terms of the GNU General Public
 * License version 2. This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#include <asm/arch/tegra-regs.h>

		.macro	disable_fiq
		.endm
		.macro	get_irqnr_and_base, irqnr, irqstat, base, tmp
		.endm

